--
-- PostgreSQL database dump
--

-- Dumped from database version 10.23 (Ubuntu 10.23-1.pgdg20.04+1)
-- Dumped by pg_dump version 15.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *not* creating schema, since initdb creates it


ALTER SCHEMA public OWNER TO postgres;

SET default_tablespace = '';

--
-- Name: ajusteestoque; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ajusteestoque (
    codigo integer NOT NULL,
    motivo character varying(255),
    dataajuste date,
    quantidade numeric(10,2),
    tipo character varying(50),
    produto integer
);


ALTER TABLE public.ajusteestoque OWNER TO postgres;

--
-- Name: ajusteestoque_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ajusteestoque ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ajusteestoque_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: caixa; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.caixa (
    codigo integer NOT NULL,
    venda integer,
    descricao character varying(255),
    datalancamento timestamp without time zone,
    valorbaixa numeric(10,3),
    tipo character varying(50)
);


ALTER TABLE public.caixa OWNER TO postgres;

--
-- Name: caixa_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.caixa ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.caixa_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cidade; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cidade (
    codigo integer NOT NULL,
    nome character varying(255),
    uf character(2)
);


ALTER TABLE public.cidade OWNER TO postgres;

--
-- Name: cidade_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cidade ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cidade_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cliente; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cliente (
    codigo integer NOT NULL,
    nome character varying(255),
    endereco character varying(255),
    bairro character varying(255),
    contato text,
    cpf character varying(25),
    limitecredito numeric(10,2) DEFAULT 0.00,
    ativo character(1) DEFAULT 'T'::bpchar,
    datacadastro date,
    cidade integer
);


ALTER TABLE public.cliente OWNER TO postgres;

--
-- Name: cliente_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cliente ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cliente_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: condicaopagamento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.condicaopagamento (
    codigo integer NOT NULL,
    numeroparcelas integer,
    descricao character varying(255)
);


ALTER TABLE public.condicaopagamento OWNER TO postgres;

--
-- Name: condicaopagamento_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.condicaopagamento ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.condicaopagamento_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estabelecimento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estabelecimento (
    codigo integer NOT NULL,
    nome character varying(255),
    contato text,
    endereco character varying(255),
    bairro character varying(255),
    cnpj character varying(25),
    cidade integer
);


ALTER TABLE public.estabelecimento OWNER TO postgres;

--
-- Name: estabelecimento_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.estabelecimento ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estabelecimento_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: estoque; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estoque (
    codigo integer NOT NULL,
    descricao character varying(255),
    quantidade numeric(10,3),
    tipo character varying(50),
    produto integer,
    origemevento character varying(255)
);


ALTER TABLE public.estoque OWNER TO postgres;

--
-- Name: estoque_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.estoque ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estoque_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: formapagamento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formapagamento (
    codigo integer NOT NULL,
    aparecercaixa character(1) DEFAULT 'T'::bpchar,
    descricao character varying(255),
    compensado character(1) DEFAULT 'T'::bpchar
);


ALTER TABLE public.formapagamento OWNER TO postgres;

--
-- Name: formapagmento_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.formapagamento ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formapagmento_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fornecedor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fornecedor (
    codigo integer NOT NULL,
    nome character varying(255),
    cpf character varying(25),
    bairro character varying(255),
    endereco character varying(255),
    contato text,
    ativo character(1) DEFAULT 'T'::bpchar,
    cidade integer
);


ALTER TABLE public.fornecedor OWNER TO postgres;

--
-- Name: fornecedor_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fornecedor ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fornecedor_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: funcionario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.funcionario (
    codigo integer NOT NULL,
    nome character varying(255),
    cpf character varying(25),
    bairro character varying(255),
    endereco character varying(255),
    login character varying(255),
    senha character varying(255),
    ativo character(1) DEFAULT 'T'::bpchar,
    cidade integer
);


ALTER TABLE public.funcionario OWNER TO postgres;

--
-- Name: funcionario_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.funcionario ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.funcionario_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: funcionariopermissao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.funcionariopermissao (
    codigo integer NOT NULL,
    funcionario integer,
    permissao integer
);


ALTER TABLE public.funcionariopermissao OWNER TO postgres;

--
-- Name: funcionariopermissao_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.funcionariopermissao ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.funcionariopermissao_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grupo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.grupo (
    codigo integer NOT NULL,
    descricao character varying(255)
);


ALTER TABLE public.grupo OWNER TO postgres;

--
-- Name: grupo_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.grupo ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grupo_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: itemvenda; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.itemvenda (
    codigo integer NOT NULL,
    quantidade numeric(10,3),
    valorunitario numeric(10,3),
    totalunitario numeric(10,3),
    produto integer,
    venda integer
);


ALTER TABLE public.itemvenda OWNER TO postgres;

--
-- Name: itemvenda_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.itemvenda ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.itemvenda_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parcela; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parcela (
    codigo integer NOT NULL,
    valorparcela numeric(10,3),
    dataemissao date,
    datavencimento date,
    quitada character(1) DEFAULT 'T'::bpchar,
    numeroparcela character varying(50),
    recebimento integer
);


ALTER TABLE public.parcela OWNER TO postgres;

--
-- Name: parcela_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parcela ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parcela_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permissao (
    codigo integer NOT NULL,
    descricao character varying(255)
);


ALTER TABLE public.permissao OWNER TO postgres;

--
-- Name: permissao_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permissao ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissao_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: produto; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.produto (
    codigo integer NOT NULL,
    descricao character varying(255),
    margem numeric(10,3),
    precocusto numeric(10,3),
    precovenda numeric(10,3),
    fornecedor integer,
    grupo integer
);


ALTER TABLE public.produto OWNER TO postgres;

--
-- Name: produto_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.produto ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produto_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recebimento; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recebimento (
    codigo integer NOT NULL,
    valor numeric(10,3),
    dataemissao date,
    datavencimento date,
    quitada character(1) DEFAULT 'T'::bpchar,
    venda integer,
    condicaopagamento integer,
    formapagamento integer
);


ALTER TABLE public.recebimento OWNER TO postgres;

--
-- Name: recebimento_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recebimento ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recebimento_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: venda; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.venda (
    codigo integer NOT NULL,
    datacriacao timestamp without time zone,
    totalvenda numeric(10,2),
    cliente integer
);


ALTER TABLE public.venda OWNER TO postgres;

--
-- Name: venda_codigo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.venda ALTER COLUMN codigo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.venda_codigo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: ajusteestoque; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: caixa; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: cidade; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.cidade VALUES (1, 'Cândido Mota', 'SP');


--
-- Data for Name: cliente; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: condicaopagamento; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: estabelecimento; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.estabelecimento VALUES (1, NULL, NULL, NULL, NULL, NULL, 1);


--
-- Data for Name: estoque; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: formapagamento; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: fornecedor; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: funcionario; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.funcionario VALUES (1, 'daniel', NULL, NULL, NULL, '1', '1', 'T', NULL);


--
-- Data for Name: funcionariopermissao; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.funcionariopermissao VALUES (1, 1, 1);


--
-- Data for Name: grupo; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: itemvenda; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: parcela; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: permissao; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.permissao VALUES (1, 'Alterar Estabelecimento');


--
-- Data for Name: produto; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: recebimento; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: venda; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Name: ajusteestoque_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ajusteestoque_codigo_seq', 1, false);


--
-- Name: caixa_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.caixa_codigo_seq', 1, false);


--
-- Name: cidade_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cidade_codigo_seq', 1, false);


--
-- Name: cliente_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cliente_codigo_seq', 1, false);


--
-- Name: condicaopagamento_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.condicaopagamento_codigo_seq', 1, false);


--
-- Name: estabelecimento_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.estabelecimento_codigo_seq', 1, false);


--
-- Name: estoque_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.estoque_codigo_seq', 1, false);


--
-- Name: formapagmento_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.formapagmento_codigo_seq', 1, false);


--
-- Name: fornecedor_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fornecedor_codigo_seq', 1, false);


--
-- Name: funcionario_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.funcionario_codigo_seq', 1, true);


--
-- Name: funcionariopermissao_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.funcionariopermissao_codigo_seq', 1, false);


--
-- Name: grupo_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.grupo_codigo_seq', 1, false);


--
-- Name: itemvenda_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.itemvenda_codigo_seq', 1, false);


--
-- Name: parcela_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.parcela_codigo_seq', 1, false);


--
-- Name: permissao_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.permissao_codigo_seq', 9, true);


--
-- Name: produto_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.produto_codigo_seq', 1, false);


--
-- Name: recebimento_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recebimento_codigo_seq', 1, false);


--
-- Name: venda_codigo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.venda_codigo_seq', 1, false);


--
-- Name: estabelecimento cnpj_estabelecimento_un; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estabelecimento
    ADD CONSTRAINT cnpj_estabelecimento_un UNIQUE (cnpj);


--
-- Name: ajusteestoque codigo_ajusteestoque_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ajusteestoque
    ADD CONSTRAINT codigo_ajusteestoque_pk PRIMARY KEY (codigo);


--
-- Name: caixa codigo_caixa_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caixa
    ADD CONSTRAINT codigo_caixa_pk PRIMARY KEY (codigo);


--
-- Name: cliente codigo_cliente_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT codigo_cliente_pk PRIMARY KEY (codigo);


--
-- Name: condicaopagamento codigo_condicaopagamento_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.condicaopagamento
    ADD CONSTRAINT codigo_condicaopagamento_pk PRIMARY KEY (codigo);


--
-- Name: estabelecimento codigo_estabelecimento_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estabelecimento
    ADD CONSTRAINT codigo_estabelecimento_pk PRIMARY KEY (codigo);


--
-- Name: estoque codigo_estoque_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estoque
    ADD CONSTRAINT codigo_estoque_pk PRIMARY KEY (codigo);


--
-- Name: formapagamento codigo_formapagmento_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formapagamento
    ADD CONSTRAINT codigo_formapagmento_pk PRIMARY KEY (codigo);


--
-- Name: fornecedor codigo_fornecedor_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fornecedor
    ADD CONSTRAINT codigo_fornecedor_pk PRIMARY KEY (codigo);


--
-- Name: funcionario codigo_funcionario_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funcionario
    ADD CONSTRAINT codigo_funcionario_pk PRIMARY KEY (codigo);


--
-- Name: funcionariopermissao codigo_funcionariopermissao_fk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funcionariopermissao
    ADD CONSTRAINT codigo_funcionariopermissao_fk PRIMARY KEY (codigo);


--
-- Name: grupo codigo_grupo_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grupo
    ADD CONSTRAINT codigo_grupo_pk PRIMARY KEY (codigo);


--
-- Name: itemvenda codigo_itemvenda_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.itemvenda
    ADD CONSTRAINT codigo_itemvenda_pk PRIMARY KEY (codigo);


--
-- Name: parcela codigo_parcela_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parcela
    ADD CONSTRAINT codigo_parcela_pk PRIMARY KEY (codigo);


--
-- Name: permissao codigo_permissao_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissao
    ADD CONSTRAINT codigo_permissao_pk PRIMARY KEY (codigo);


--
-- Name: produto codigo_produto_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT codigo_produto_pk PRIMARY KEY (codigo);


--
-- Name: recebimento codigo_recebimento_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recebimento
    ADD CONSTRAINT codigo_recebimento_pk PRIMARY KEY (codigo);


--
-- Name: venda codigo_venda_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venda
    ADD CONSTRAINT codigo_venda_pk PRIMARY KEY (codigo);


--
-- Name: cliente cpf_nome_cliente_un; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cpf_nome_cliente_un UNIQUE (cpf, nome);


--
-- Name: fornecedor cpf_nome_fornecedor_un; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fornecedor
    ADD CONSTRAINT cpf_nome_fornecedor_un UNIQUE (cpf, nome);


--
-- Name: funcionario cpf_nome_funcionario_un; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funcionario
    ADD CONSTRAINT cpf_nome_funcionario_un UNIQUE (cpf, nome);


--
-- Name: condicaopagamento descricao_condicaopagamento_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.condicaopagamento
    ADD CONSTRAINT descricao_condicaopagamento_pk UNIQUE (descricao);


--
-- Name: grupo descricao_grupo_un; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.grupo
    ADD CONSTRAINT descricao_grupo_un UNIQUE (descricao);


--
-- Name: permissao descricao_permissao_un; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissao
    ADD CONSTRAINT descricao_permissao_un UNIQUE (descricao);


--
-- Name: produto descricao_produto_un; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT descricao_produto_un UNIQUE (descricao);


--
-- Name: cidade id_cidade_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cidade
    ADD CONSTRAINT id_cidade_pk PRIMARY KEY (codigo);


--
-- Name: cidade nome_cidade_un; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cidade
    ADD CONSTRAINT nome_cidade_un UNIQUE (nome);


--
-- Name: cliente cidade_cliente_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cliente
    ADD CONSTRAINT cidade_cliente_fk FOREIGN KEY (cidade) REFERENCES public.cidade(codigo);


--
-- Name: estabelecimento cidade_estabelecimento_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estabelecimento
    ADD CONSTRAINT cidade_estabelecimento_fk FOREIGN KEY (cidade) REFERENCES public.cidade(codigo);


--
-- Name: fornecedor cidade_fornecedor_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fornecedor
    ADD CONSTRAINT cidade_fornecedor_fk FOREIGN KEY (cidade) REFERENCES public.cidade(codigo);


--
-- Name: funcionario cidade_funcionario_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funcionario
    ADD CONSTRAINT cidade_funcionario_fk FOREIGN KEY (cidade) REFERENCES public.cidade(codigo);


--
-- Name: venda cliente_venda_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.venda
    ADD CONSTRAINT cliente_venda_fk FOREIGN KEY (cliente) REFERENCES public.cliente(codigo);


--
-- Name: recebimento condicaopagamento_recebimento_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recebimento
    ADD CONSTRAINT condicaopagamento_recebimento_fk FOREIGN KEY (condicaopagamento) REFERENCES public.condicaopagamento(codigo);


--
-- Name: recebimento formapagamento_recebimento_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recebimento
    ADD CONSTRAINT formapagamento_recebimento_fk FOREIGN KEY (formapagamento) REFERENCES public.formapagamento(codigo);


--
-- Name: produto fornecedor_produto_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT fornecedor_produto_fk FOREIGN KEY (fornecedor) REFERENCES public.fornecedor(codigo);


--
-- Name: funcionariopermissao funcionario_funcionariopermissao_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funcionariopermissao
    ADD CONSTRAINT funcionario_funcionariopermissao_fk FOREIGN KEY (funcionario) REFERENCES public.funcionario(codigo);


--
-- Name: produto grupo_produto_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.produto
    ADD CONSTRAINT grupo_produto_fk FOREIGN KEY (grupo) REFERENCES public.grupo(codigo);


--
-- Name: funcionariopermissao permissao_funcionariopermissao_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funcionariopermissao
    ADD CONSTRAINT permissao_funcionariopermissao_fk FOREIGN KEY (permissao) REFERENCES public.permissao(codigo);


--
-- Name: ajusteestoque produto_ajusteestoque_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ajusteestoque
    ADD CONSTRAINT produto_ajusteestoque_fk FOREIGN KEY (produto) REFERENCES public.produto(codigo);


--
-- Name: estoque produto_estoque_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estoque
    ADD CONSTRAINT produto_estoque_fk FOREIGN KEY (produto) REFERENCES public.produto(codigo);


--
-- Name: itemvenda produto_itemvenda_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.itemvenda
    ADD CONSTRAINT produto_itemvenda_fk FOREIGN KEY (produto) REFERENCES public.produto(codigo);


--
-- Name: parcela recebimento_parcela_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parcela
    ADD CONSTRAINT recebimento_parcela_fk FOREIGN KEY (recebimento) REFERENCES public.recebimento(codigo);


--
-- Name: caixa venda_caixa_pk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caixa
    ADD CONSTRAINT venda_caixa_pk FOREIGN KEY (venda) REFERENCES public.venda(codigo);


--
-- Name: itemvenda venda_itemvenda_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.itemvenda
    ADD CONSTRAINT venda_itemvenda_fk FOREIGN KEY (venda) REFERENCES public.venda(codigo);


--
-- Name: recebimento venda_recebimento_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recebimento
    ADD CONSTRAINT venda_recebimento_fk FOREIGN KEY (venda) REFERENCES public.venda(codigo);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;


--
-- PostgreSQL database dump complete
--

